"use client"

import { useState } from "react"
import axios from "axios"
import { RefreshCw, Plus, Loader2, BookOpen } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { toast } from "sonner"
import { DashboardTile } from "@/types/report"
import { useQueryClient } from "@tanstack/react-query"

interface DataStoryCardProps {
    fileId: string
    story: string
    generatedAt: string
    onRegenerate: () => Promise<void>
    isRegenerating: boolean
}

export function DataStoryCard({
    fileId,
    story,
    generatedAt,
    onRegenerate,
    isRegenerating
}: DataStoryCardProps) {
    const [isAddingToReport, setIsAddingToReport] = useState(false)
    const queryClient = useQueryClient()

    const handleAddToReport = async () => {
        setIsAddingToReport(true)

        try {
            // Get or create report for this file
            const reportsRes = await axios.get(`/api/v1/reports?file_id=${fileId}`)
            let reportId: string

            if (reportsRes.data.length > 0) {
                reportId = reportsRes.data[0].report_id
            } else {
                // Create new report
                const createRes = await axios.post("/api/v1/reports", {
                    title: "Custom Report",
                    file_id: fileId
                })
                reportId = createRes.data.report_id
            }

            // Create tile for the story
            const tile: DashboardTile = {
                tile_id: `story_${Date.now()}`,
                type: "text",
                title: "Data Story",
                data: {
                    content: story,
                    generated_at: generatedAt
                },
                config: {
                    variant: "story"
                },
                source: {
                    file_id: fileId
                }
            }

            // Add tile to report via API
            await axios.post(`/api/v1/reports/${reportId}/tiles`, tile)

            // Invalidate report queries to refresh Custom Report tab
            queryClient.invalidateQueries({ queryKey: ["reports", fileId] })
            queryClient.invalidateQueries({ queryKey: ["report", reportId] })
            queryClient.invalidateQueries({ queryKey: ["report"] })

            toast.success("Data Story added to Custom Report")
        } catch (error) {
            console.error("Failed to add story to report:", error)
            toast.error("Failed to add story to report")
        } finally {
            setIsAddingToReport(false)
        }
    }

    // Format the timestamp for display
    const formattedTime = new Date(generatedAt).toLocaleString()

    return (
        <Card className="border-violet-200 dark:border-violet-800 bg-gradient-to-br from-violet-50/50 to-white dark:from-violet-950/20 dark:to-neutral-900 shadow-md">
            <CardHeader className="pb-3">
                <div className="flex items-center gap-2">
                    <BookOpen className="w-5 h-5 text-violet-500" />
                    <CardTitle className="text-lg font-semibold text-violet-700 dark:text-violet-300">
                        Data Story
                    </CardTitle>
                </div>
            </CardHeader>
            <CardContent className="pb-4">
                <p className="text-neutral-700 dark:text-neutral-300 leading-relaxed whitespace-pre-wrap">
                    {story}
                </p>
            </CardContent>
            <CardFooter className="flex flex-col gap-3 pt-0">
                <p className="text-xs text-neutral-500 w-full">
                    Generated by AI based on current data insights • {formattedTime}
                </p>
                <div className="flex gap-2 w-full">
                    <Button
                        variant="outline"
                        size="sm"
                        onClick={onRegenerate}
                        disabled={isRegenerating}
                        className="gap-1.5"
                    >
                        {isRegenerating ? (
                            <Loader2 className="w-4 h-4 animate-spin" />
                        ) : (
                            <RefreshCw className="w-4 h-4" />
                        )}
                        Regenerate
                    </Button>
                    <Button
                        variant="outline"
                        size="sm"
                        onClick={handleAddToReport}
                        disabled={isAddingToReport}
                        className="gap-1.5"
                    >
                        {isAddingToReport ? (
                            <Loader2 className="w-4 h-4 animate-spin" />
                        ) : (
                            <Plus className="w-4 h-4" />
                        )}
                        Add to Custom Report
                    </Button>
                </div>
            </CardFooter>
        </Card>
    )
}
